import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { serve } from './serve.mjs';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { readFileSync } from 'node:fs';
const dist=resolve('dist');
const server=await serve({TibReading:dist,app:dist},4188);
const browser=await chromium.launch();
try {
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'allow'});
  const page=await context.newPage();page.setDefaultTimeout(10000);
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  const external=[]; page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:4188/'))external.push(r.url());});
  const base='http://127.0.0.1:4188/TibReading/';
  await page.goto(base+'#/practice');
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('.sidebar').isVisible(),false);
  assert.equal(await page.locator('.bottom-nav').isVisible(),true);
  await page.getByRole('button',{name:'More',exact:true}).click();
  await page.getByRole('dialog',{name:'All sections'}).waitFor();
  await page.locator('.menu-item').filter({hasText:'Builder'}).click();
  await page.getByRole('heading',{name:'Syllable Builder',exact:true}).waitFor();
  for(const tab of ['intro','alphabet','vowels','stacks','practice','builder','rules','trace','read','proverbs','settings']) {
    await page.evaluate(t=>location.hash='#/'+t,tab);
    await page.waitForFunction(t=>document.querySelector('.app')?.dataset.screenLabel==='00 '+t,tab);
    await page.waitForTimeout(100);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
    assert.equal(overflow,false,tab+' horizontal overflow at 390px');
    const targets=await page.locator('.bottom-nav button').evaluateAll(bs=>bs.map(b=>({w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})));
    assert.ok(targets.every(r=>r.w>=44&&r.h>=44));
  }
  await page.evaluate(()=>location.hash='#/practice');
  await page.getByLabel('Session length',{exact:true}).selectOption('5');
  await page.getByRole('button',{name:'Start session',exact:true}).click();
  await page.locator('.answer-option').first().click();
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('tibreading.progress')).items);
  const keys=await page.evaluate(()=>caches.keys());assert.ok(keys.some(k=>k.startsWith('tibreading:/TibReading/:')));
  const cached=await page.evaluate(async()=>{const key=(await caches.keys()).find(k=>k.startsWith('tibreading:/TibReading/:'));return (await(await caches.open(key)).keys()).map(r=>r.url);});
  assert.ok(cached.some(u=>u.endsWith('.woff2')));
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading',{name:'Practice',exact:true}).waitFor();
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('tibreading.progress')).items),saved);
  await page.evaluate(()=>document.fonts.ready);
  assert.ok(await page.evaluate(()=>document.fonts.check('24px "Noto Serif Tibetan"','བསྒྲུབས')));
  await page.getByRole('button',{name:'Read',exact:true}).click();
  await page.getByRole('heading',{name:'Reading path',exact:true}).waitFor();
  await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--paper').trim()),'#211f1c');
  assert.deepEqual(external,[]);assert.deepEqual(errors,[]);
  await context.close();
  // Opening the build as a local file remains useful without a web server.
  const file=await browser.newPage();
  const fileErrors=[];file.on('pageerror',e=>fileErrors.push(e.message));
  await file.goto(pathToFileURL(resolve(dist,'index.html')).href+'#/practice');
  await file.getByRole('heading',{name:'Practice',exact:true}).waitFor();
  assert.deepEqual(fileErrors,[]);
  assert.ok(!readFileSync(resolve(dist,'index.html'),'utf8').includes('src="/assets/'));
  const futurePage=await browser.newPage();
  await futurePage.addInitScript(()=>localStorage.setItem('tibreading.progress',JSON.stringify({version:99,precious:'future progress'})));
  await futurePage.goto('http://127.0.0.1:4188/app/#/practice');
  await futurePage.getByText(/Saved progress could not be read and has been preserved/).waitFor();
  assert.equal(await futurePage.evaluate(()=>JSON.parse(localStorage.getItem('tibreading.progress')).version),99);
  const rootPage=await browser.newPage();
  await rootPage.goto('http://127.0.0.1:4188/app/#/builder');
  await rootPage.getByRole('heading',{name:'Syllable Builder',exact:true}).waitFor();
  console.log('check:offline-mobile — subpath cache, offline reload/fonts/progress, mobile navigation/layout, dark/reduced-motion, file:// and relative hosting passed');
} finally {await browser.close();server.close();}
